services:
  scalable:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: flask
    ports:
      - "5000:5000"
      - "5432:5432"
    depends_on:
      - keydb
    environment:
      - OLLAMA_BASE=http://host.docker.internal:11434
      - OLLAMA_ENDPOINT=http://host.docker.internal:11434/api/generate
      - APP_HOST=0.0.0.0
      - FLASK_ENV=development
      - REDIS_HOST=keydb
      - REDIS_PORT=6379
      - SPORE_DATA_DIR=/app/data
      - KERNEL_DATA_MOUNT=/data
    volumes:
      - ..:/app
      - spore_data:/data

  keydb:
    image: eqalpha/keydb:latest
    container_name: keydb
    ports:
      - "6379:6379"
    restart: always

volumes:
  spore_data: